### ISSUE TITLE
Web: reading task screen 

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#147]
### User Story
**As a** user of the application,  
**I want** a reading tasks screen where I can view the list of books I am currently reading and add new books,  
**So that** I can easily manage my reading tasks and track my progress.

### Acceptance Criteria
- [ ] Design and implement a reading tasks screen in the application.
- [ ] Display a list of the books the user is currently reading on the reading tasks screen.
- [ ] Provide an option to add new books to the reading list.
- [ ] Ensure that the reading tasks screen is accessible from the application's navigation.
- [ ] Implement functionality to add new books to the reading list and update the database accordingly.
- [ ] Test the reading tasks screen to verify accurate display of reading tasks and functionality to add new books.
- [ ] Ensure responsiveness and usability of the reading tasks screen across different devices and screen sizes.
- [ ] Document any changes made to the codebase for future reference.

### Related Issues
- None

### Notes
- Providing a dedicated reading tasks screen allows users to easily manage their reading lists and track their progress.
- Collaborate with frontend developers to ensure proper integration of the reading tasks screen into the application's interface.
<img width="1076" alt="Screenshot 2024-03-23 at 7 10 43 PM" src="https://github.com/uiowaSEP2024/001_DisAv/assets/56485548/429ca669-3724-434e-ab00-f471230f5c9d">

### Tasks
- [ ] Design the layout and interface for the reading tasks screen in the application.
- [ ] Implement functionality to fetch and display the list of books the user is currently reading.
- [ ] Provide an option for users to add new books to the reading list.
- [ ] Implement logic to update the database with new book entries.
- [ ] Test the reading tasks screen to verify accurate display of reading tasks and functionality to add new books.
- [ ] Ensure responsiveness and usability of the reading tasks screen across different devices and screen sizes.
- [ ] Document any changes made to the codebase.

**Comment by aezouhri** [comment]
Starting to work on this issue.
