### ISSUE TITLE
Mobile: add books (depends on #149)

### ISSUE THREAD

**Issue by saanbe16** [uiowaSEP2024/001_DisAv#154]
### User Story
**As a** user of the application,  
**I want** to be able to add a new book to my reading list,  
**So that** I can keep track of books I plan to read.

### Acceptance Criteria
- [ ] Implement a feature in the application that allows users to add a new book to their reading list.
- [ ] Provide a form or interface where users can enter details such as the title, author, genre, and other relevant information of the new book.
- [ ] Ensure that the entered book details are properly validated before being added to the reading list.
- [ ] Update the database with the new book entry upon successful submission.
- [ ] Display a confirmation message to the user upon successful addition of the new book.
- [ ] Test the functionality to add a new book to the reading list to verify accurate data submission and database update.
- [ ] Ensure responsiveness and usability of the book addition feature across different devices and screen sizes.
- [ ] Document any changes made to the codebase for future reference.

### Related Issues
- None

### Notes
- Allowing users to add new books to their reading list enhances the flexibility and cust
<img width="841" alt="Screenshot 2024-03-23 at 7 24 09 PM" src="https://github.com/uiowaSEP2024/001_DisAv/assets/56485548/f8941578-3b46-4cbe-8f5e-8d9eb5c53aff">
omization of their reading experience.
- Collaborate with frontend developers to ensure seamless integration of the book addition feature into the application's interface.

### Tasks
- [ ] Design the form or interface for adding a new book to the reading list.
- [ ] Implement validation logic to ensure proper input of book details.
- [ ] Update the database schema to accommodate new book entries.
- [ ] Implement functionality to submit and process new book entries in the backend.
- [ ] Test the functionality to add a new book to the reading list across different devices and screen sizes.
- [ ] Ensure proper error handling and validation in the book addition feature.
- [ ] Document any changes made to the codebase.

**Comment by bdesollar** [comment]
Starting this on Mobile

**Comment by saanbe16** [comment]
Irrelevant now
