### ISSUE TITLE
Web: update preferences

### ISSUE THREAD

**Issue by aezouhri** [uiowaSEP2024/001_DisAv#47]
### User Story
**As a** user,  
**I want** to update my account preferences,  
**So that** activities suggested during time out are interesting for me.

### Acceptance Criteria
- [ ] Design a user friendly form with activities to fill
- [ ] Save such form in the database
- [ ] Link such form to the account
- [ ] Ability to update the form at any given time

### Related Issues
- #[Issue number] - [Issue name]

### Notes
- Updating information in a database is irreversible
- Ensure the data is saved before moving to another page or logging out
- Data needs to be displayed when visiting preferences page

### Tasks
- [ ] Design user interface for filling a form
- [ ] Connect database to form submission (API Back-end integration)
- [ ] Connect account to form data in database if preferences are already present (API Back-end integration)

**Comment by saanbe16** [comment]
this was completed successfully
